name: "🚀 RELEASE: To WordPress.org"
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - name: WordPress Plugin Deploy
        uses: 10up/actions-wordpress/dotorg-plugin-deploy@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: "olympus-google-fonts"
